name: CUPS
version: "1.0.5"
slug: cupsik
description: A CUPS print server with working AirPrint
arch:
  - amd64
  - aarch64
usb: true
init: false
homeassistant_api: true
host_network: true
ports:
  631/tcp: 631
  631/udp: 631
ports_description:
  631/tcp: For other devices on the local network to print to this server
  631/udp: For other devices on the local network to print to this server
webui: https://[HOST]:[PORT:631]/
# ingress: true
# ingress_stream: true
map:
  - config:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?

